site_name: Fanart.tv Wiki
site_description: Welcome to the Fanart.tv Docs
site_author: akovia
site_url: https://wiki.fanart.tv

repo_url: https://github.com/KodeStar/fanartwiki
repo_name: fanart.tv/site-documentation
edit_uri: ""

plugins:
  - search
  
markdown_extensions:
  - smarty
  - pymdownx.details
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  
theme:
  name: material
  features:
    - navigation.instant
  language: en
  favicon: assets/images/favicon.ico
  logo: assets/images/fatv-logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
nav:
    - Home: 'index.md'
    - FAQ: 'General/faq.md'
    - 'Site Information':
        - 'Site Rules': 'General/site rules.md'
        - 'Site Vision': 'General/general rules and vision.md'
        - 'Unwritten Rules': 'General/unwritten rules revealed.md'
    - Image Rules:
        Movie Images:
            - 'HD MovieLogo': 'ImageTypes/Movies/hdmovielogo.md' 
            - 'HD MovieClearart': 'ImageTypes/Movies/hdmovieclearart.md' 
            - 'Movie Poster': 'ImageTypes/Movies/movieposter.md' 
            - 'Movie Background': 'ImageTypes/Movies/moviebackground.md' 
            - 'Movie Disc': 'ImageTypes/Movies/moviedisc.md' 
            - 'Movie Thumb': 'ImageTypes/Movies/moviethumb.md' 
            - 'Movie Banner': 'ImageTypes/Movies/moviebanner.md' 
        TV Images:
            - 'HD ClearLogo': 'ImageTypes/TV/hdtvlogo.md' 
            - 'HD ClearART': 'ImageTypes/TV/hdclearart.md' 
            - 'TV Poster': 'ImageTypes/TV/tvposter.md' 
            - 'Season Poster': 'ImageTypes/TV/seasonposter.md' 
            - 'Character Art': 'ImageTypes/TV/characterart.md' 
            - 'TV Background': 'ImageTypes/TV/showbackground.md' 
            - 'TV Banner': 'ImageTypes/TV/tvbanner.md' 
            - 'Season Banner': 'ImageTypes/TV/seasonbanner.md' 
            - 'TV Thumb': 'ImageTypes/TV/tvthumb.md' 
            - 'Season Thumb': 'ImageTypes/TV/seasonthumb.md' 
        Music Images:
            - 'HD MusicLogo': 'ImageTypes/Music/hdmusiclogo.md' 
            - 'Album Cover': 'ImageTypes/Music/albumcover.md' 
            - 'Artist Thumb': 'ImageTypes/Music/artistthumb.md' 
            - 'CDArt': 'ImageTypes/Music/cdart.md' 
            - 'Artist Background': 'ImageTypes/Music/artistbackground.md' 
            - 'Music Banner': 'ImageTypes/Music/musicbanner.md' 
            - 'Record Label': 'ImageTypes/Music/musiclabel.md' 
    - Guides:
        - 'Replace an Image': 'General/replace an image.md'
        