site_name: Fanart.tv Wiki
site_description: Welcome to the Fanart.tv Docs
site_author: akovia
site_url: https://wiki.fanart.tv

repo_url: https://github.com/KodeStar/fanartwiki
repo_name: fanart.tv/site-documentation
edit_uri: ""

plugins:
  - search
  
markdown_extensions:
   - smarty

theme:
  name: material
  features:
    - navigation.instant
  language: en
  favicon: assets/images/favicon.ico
  logo: assets/images/fatv-logo.png
  palette:
    primary: royal
    accent: indigo
  
nav:
    - Home: 'index.md'
    - FAQ: 'General/faq.md'
    - Rules:
        Movie Images:
            - HD-MovieLogo: 'ImageTypes/Movies/hdmovielogo.md' 
            - HD-MovieClearart: 'ImageTypes/Movies/hdmovieclearart.md' 
            - MoviePoster: 'ImageTypes/Movies/movieposter.md' 
            - MovieBackground: 'ImageTypes/Movies/moviebackground.md' 
            - MovieDisc: 'ImageTypes/Movies/moviedisc.md' 
            - MovieThumb: 'ImageTypes/Movies/moviethumb.md' 
            - MovieBanner: 'ImageTypes/Movies/moviebanner.md' 
        TV Images:
            - HD-TVLogo: 'ImageTypes/TV/hdtvlogo.md' 
            - HD-Clearart: 'ImageTypes/TV/hdclearart.md' 
            - HD-TVPoster: 'ImageTypes/TV/tvposter.md' 
            - SeasonPoster: 'ImageTypes/TV/seasonposter.md' 
            - Characterart: 'ImageTypes/TV/characterart.md' 
            - ShowBackground: 'ImageTypes/TV/showbackground.md' 
            - TVBanner: 'ImageTypes/TV/tvbanner.md' 
            - Season-Banner: 'ImageTypes/TV/seasonbanner.md' 
            - TVThumb: 'ImageTypes/TV/tvthumb.md' 
            - Season-Thumb: 'ImageTypes/TV/seasonthumb.md' 
        Music Images:
            - HD-MusicLogo: 'ImageTypes/Music/hdmusiclogo.md' 
            - AlbumCover: 'ImageTypes/Music/albumcover.md' 
            - ArtistThumb: 'ImageTypes/Music/artistthumb.md' 
            - CDArt: 'ImageTypes/Music/cdart.md' 
            - ArtistBackground: 'ImageTypes/Music/artistbackground.md' 
            - MusicBanner: 'ImageTypes/Music/musicbanner.md' 
            - RecordLabel: 'ImageTypes/Music/musiclabel.md' 
    - Guides:
        - 'Replace an Image': 'General/Replace an Image.md'
        